DELETE FROM stg_%REFERENCE_TABLE_NAME%;
DROP SEQUENCE IF EXISTS stg_%REFERENCE_TABLE_NAME%_seq;
CREATE SEQUENCE stg_%REFERENCE_TABLE_NAME%_seq AS INT START WITH 1;
CREATE OR REPLACE FUNCTION stg_%REFERENCE_TABLE_NAME%_id() RETURNS TRIGGER LANGUAGE PLPGSQL AS $$ BEGIN IF NEW.id is NULL THEN NEW.id = nextval('stg_%REFERENCE_TABLE_NAME%_seq'); END IF; RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS trig_%REFERENCE_TABLE_NAME%_id ON stg_%REFERENCE_TABLE_NAME%;
CREATE TRIGGER trig_%REFERENCE_TABLE_NAME%_id BEFORE INSERT ON stg_%REFERENCE_TABLE_NAME% FOR EACH ROW EXECUTE procedure stg_%REFERENCE_TABLE_NAME%_id();
