services:
  web:
    platform: linux/x86_64
    container_name: protectedplanet-web
    build: .
    command: /bin/bash -l -c "rm -rf /ProtectedPlanet/tmp/pids/server.pid;bundle i;PUPPETEER_SKIP_DOWNLOAD=true yarn install; bundle exec rails db:migrate; bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ProtectedPlanet
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519
      - ./node_modules:/ProtectedPlanet/node_modules
      - protectedplanet_bundler:/usr/local/bundle
      - /run/host-services/ssh-auth.sock:/ssh-agent # Use this setting for Mac OS X and comment out ${SSH_AUTH_SOCK}:/ssh-agent below
    ports:
      - "3000:3000"
    networks:
      - protectedplanet
    env_file:
      - '.env'
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    depends_on:
      - db
      - redis
      - elasticsearch
      - webpacker
    stdin_open: true
    tty: true    
    # In order for container to be able to find servers
    dns:
      - 1.1.1.1
      - 8.8.8.8
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    platform: linux/x86_64
    container_name: protectedplanet-db
    image: kartoza/postgis:11.5-2.5
    ports:
      - "5441:5432"
    networks:
      - protectedplanet
    env_file:
      - '.env'
    volumes:
      - protectedplanet_pg_data:/var/lib/postgresql
      - ./entrypoints/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: protectedplanet-redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - protectedplanet
    env_file:
      - '.env'
    volumes:
      - protectedplanet_redis_data:/data
  sidekiq:
    platform: linux/x86_64
    build: .
    volumes:
      - .:/ProtectedPlanet
      - ./node_modules:/ProtectedPlanet/node_modules
      - protectedplanet_bundler:/usr/local/bundle
      # See ## Step 5: Set up Chromium Binary for more info
      - ./chrome:/ProtectedPlanet/node_modules/puppeteer/.local-chromium/linux-809590/chrome-linux
    networks:
      - protectedplanet
    env_file:
      - '.env'
    depends_on:
      - db
      - redis
    command: /bin/bash -l -c "bundle exec sidekiq"
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
  elasticsearch:
    platform: linux/x86_64
    container_name: protectedplanet-elasticsearch
    image: elasticsearch:8.6.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - protectedplanet
    env_file:
      - '.env'
    volumes:
      - 'protectedplanet_es_data:/usr/share/elasticsearch/data'
  kibana:
    # platform: linux/x86_64
    image: kibana:8.6.0
    environment:
      - ELASTICSEARCH_HOSTS=http://protectedplanet-elasticsearch:9200
    env_file:
      - '.env'
    ports:
      - "5601:5601"
    networks:
      - protectedplanet
  webpacker:
    platform: linux/x86_64
    container_name: protectedplanet-webpacker
    build: .
    command: /bin/bash -l -c "rm -rf /ProtectedPlanet/app/public/packs; bundle i;PUPPETEER_SKIP_DOWNLOAD=true yarn install; rm -rf /ProtectedPlanet/tmp/cache/webpacker; /ProtectedPlanet/docker/scripts/webpacker"
    volumes: 
      - .:/ProtectedPlanet
      - ./node_modules:/ProtectedPlanet/node_modules
      - protectedplanet_bundler:/usr/local/bundle
    ports:
      - "3035:3035"
    env_file:
      - '.env'
    networks:
      - protectedplanet
    extra_hosts:
      - "host.docker.internal:host-gateway"
  api:
    platform: linux/x86_64
    container_name: protectedplanet-api
    build:
      context: ${API_PATH}
    # Remove this once api is using the ruby 4 version
    command: /bin/bash -l -c " bundle i; bundle exec rackup --host 0.0.0.0"
    volumes:
      # This should be removed once the api is using the latest gem versions branch is merged 
      - ${API_PATH}:/ProtectedPlanetApi
      - ${API_PATH}:/app
      # Use this setting for Mac OS X and comment out ${SSH_AUTH_SOCK}:/ssh-agent below
      # The following 2 lines are probably not needed when we use ruby 4 
      # as it was for capistrano deployment but not used in ruby 4
      - /run/host-services/ssh-auth.sock:/ssh-agent 
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519
    ports:
      - "9292:9292"
    networks:
      - protectedplanet
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      # The following is probably not needed when we use ruby 4
      - SSH_AUTH_SOCK=/ssh-agent
      - RACK_ENV=development
      - MAILER_HOST=protectedplanet-mailpit
      - MAILER_ADDRESS=protectedplanet-mailpit
      - MAILER_PORT=1025
      - MAILER_DOMAIN=localhost
      - MAILER_USERNAME=dev
      - MAILER_PASSWORD=dev
      - MAILER_AUTHENTICATION=login
    depends_on:
      - db
      - mailpit
    stdin_open: true
    tty: true
    profiles: ['api']
  mailpit:
    # Mailpit is a mail server for testing and development purposes. 
    # It is used to send and receive emails. 
    # See MAILER_* enviroment section in protectedplanet-api for all needed envs
    image: axllent/mailpit:v1.29
    restart: unless-stopped
    container_name: protectedplanet-mailpit
    volumes:
      - protectedplanet_mailpit_data:/data
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - protectedplanet
    environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  protectedplanet:
    driver: bridge

volumes:
  protectedplanet_pg_data:
  protectedplanet_redis_data:
  protectedplanet_es_data:
  protectedplanet_bundler:
  protectedplanet_node_modules:
  protectedplanet_mailpit_data:
