DELETE FROM STAGING_WDPA;
DELETE FROM STAGING_SPATIAl_DATA;
DELETE FROM STAGING_WDPA_ISO_ASSOC;
DROP INDEX IF EXISTS ORIG_1;
DROP INDEX IF EXISTS ORIG_2;
DROP INDEX IF EXISTS ORIG_3;
DROP INDEX IF EXISTS ORIG_4;
DROP INDEX IF EXISTS ORIG_5;
DROP INDEX IF EXISTS ORIG_6;
CREATE INDEX ORIG_1 ON STAGING_WDPA(ORIGINATOR_ID);
CREATE INDEX ORIG_2 ON WDPA(ToZ, ORIGINATOR_ID,ISDELETED);
CREATE INDEX ORIG_3 ON STAGING_SPATIAL_DATA(ORIGINATOR_ID);
CREATE INDEX ORIG_4 ON SPATIAL_DATA(ToZ, ORIGINATOR_ID, ISDELETED);
CREATE INDEX ORIG_5 ON STAGING_WDPA_ISO_ASSOC(ORIGINATOR_ID);
CREATE INDEX ORIG_6 ON WDPA_ISO_ASSOC(ToZ, ORIGINATOR_ID, ISDELETED);

