DELETE FROM STAGING_MARINE_ENUM;

INSERT INTO STAGING_MARINE_ENUM(CODE, DESCRIPTION, ORIGINATOR_ID) VALUES(1, 'Part', 10000);
INSERT INTO STAGING_MARINE_ENUM(CODE, DESCRIPTION, ORIGINATOR_ID) VALUES(2, 'Not Reported', 10000);
INSERT INTO STAGING_MARINE_ENUM(CODE, DESCRIPTION, ORIGINATOR_ID) VALUES(3, 'Not Applicable', 10000);
INSERT INTO STAGING_MARINE_ENUM(CODE, DESCRIPTION, ORIGINATOR_ID) VALUES(4, 'All', 10000);


INSERT INTO staging_marine_enum(CODE, DEscription, Originator_id) SELECT MIN(OBJECTID), NO_TAKE, 10000 FROM wdpadata_poly_may2023 a WHERE a.NO_TAKE NOT IN (SELECT DESCRIPTION FROM MARINE_ENUM UNION SELECT DESCRIPTION FROM STAGING_MARINE_ENUM) GROUP BY NO_TAKE;