DELETE FROM staging_orig_designation_status
CREATE OR REPLACE FUNCTION staging_orig_desig_status_id() RETURNS TRIGGER LANGUAGE PLPGSQL AS $$ BEGIN IF NEW.id is NULL THEN NEW.id = hashtext(NEW.description); END IF; RETURN NEW; END; $$
DROP TRIGGER IF EXISTS trig_staging_orig_desig_status_id ON staging_orig_designation_status
CREATE TRIGGER trig_staging_orig_desig_status_id BEFORE INSERT ON staging_orig_designation_status FOR EACH ROW EXECUTE procedure staging_orig_desig_status_id()

INSERT INTO STAGING_ORIG_DESIGNATION_STATUS(DESCRIPTION, ORIGINATOR_ID) SELECT DISTINCT DESIG_ENG, 10000 FROM WDPADATA_POLY_MAY2023 UNION SELECT DISTINCT DESIG_ENG, 10000 FROM WDPADATA_POLY_MAY2023 UNION SELECT DISTINCT DESIG_ENG, 10000 FROM WDPADATA_POLY_MAY2023