DELETE FROM stg_orig_designation_status

DROP SEQUENCE IF EXISTS stg_orig_desig_seq
CREATE SEQUENCE stg_orig_desig_seq AS INT START WITH 1

CREATE OR REPLACE FUNCTION stg_orig_desig_status_id() RETURNS TRIGGER LANGUAGE PLPGSQL AS $$ BEGIN IF NEW.id is NULL THEN NEW.id = nextval('stg_orig_desig_seq'); END IF; RETURN NEW; END; $$
DROP TRIGGER IF EXISTS trig_stg_orig_desig_status_id ON stg_orig_designation_status
CREATE TRIGGER trig_stg_orig_desig_status_id BEFORE INSERT ON stg_orig_designation_status FOR EACH ROW EXECUTE procedure stg_orig_desig_status_id()

INSERT INTO stg_ORIG_DESIGNATION_STATUS(DESCRIPTION, ORIGINATOR_ID) SELECT DISTINCT DESIG_ENG, 10000 FROM WDPADATA_POLY_MAY2023 UNION SELECT DISTINCT DESIG_ENG, 10000 FROM WDPADATA_POLY_MAY2023 UNION SELECT DISTINCT DESIG_ENG, 10000 FROM WDPADATA_POLY_MAY2023